export default [
  {
    _id: "1",
    courseId: "RS101",
    title: "Quiz A",
    quizType: 1,
    availableDate: "2023-01-05",
    availableUntilDate: "2023-01-10",
    dueDate: "2023-01-10",
    points: 10,
    questionsCount: 5,
    isMultipleAvailableDates: false,
    isPublished: false,
    isShuffleAnswers: false,
    timeLimit: 20,
    isMultipleAttempts: false,
    showCorrectAnswersDate: "2021-01-11",
    isOneQuestionAtATime: false,
    isWebcamRequired: false,
    isLockQuestionsAfterAnswering: false,
  },
  {
    _id: "2",
    courseId: "RS101",
    title: "Quiz B",
    quizType: 2,
    availableDate: "2023-01-05",
    availableUntilDate: "2023-01-10",
    dueDate: "2023-01-10",
    points: 10,
    questionsCount: 5,
    isMultipleAvailableDates: false,
    isPublished: true,
    isShuffleAnswers: false,
    timeLimit: 20,
    isMultipleAttempts: false,
    showCorrectAnswersDate: "2021-01-11",
    isOneQuestionAtATime: false,
    isWebcamRequired: false,
    isLockQuestionsAfterAnswering: false,
  },
  {
    _id: "3",
    courseId: "RS101",
    title: "Quiz C",
    quizType: 3,
    availableDate: "2023-01-05",
    availableUntilDate: "2023-01-10",
    dueDate: "2023-01-10",
    points: 10,
    questionsCount: 5,
    isMultipleAvailableDates: false,
    isPublished: false,
    isShuffleAnswers: false,
    timeLimit: 20,
    isMultipleAttempts: false,
    showCorrectAnswersDate: "2021-01-11",
    isOneQuestionAtATime: false,
    isWebcamRequired: false,
    isLockQuestionsAfterAnswering: false,
  },
];
