export default [
  {
    _id: "1",
    quizId: "1",
    quizQuestionType: 1,
    title: "MCQ 1",
    questionText: "MCQ Text 1",
    points: 2,
    choices: [
      { choiceText: "Choice 1", isCorrect: true },
      { choiceText: "Choice 2", isCorrect: false },
      { choiceText: "Choice 3", isCorrect: false },
    ],
  },
  {
    _id: "2",
    quizId: "1",
    quizQuestionType: 1,
    title: "MCQ 2",
    questionText: "MCQ Text 2",
    points: 2,
    choices: [
      { choiceText: "Choice 1", isCorrect: false },
      { choiceText: "Choice 2", isCorrect: true },
      { choiceText: "Choice 3", isCorrect: false },
    ],
  },
  {
    _id: "3",
    quizId: "1",
    quizQuestionType: 1,
    title: "MCQ 2",
    questionText: "MCQ Text 3",
    points: 2,
    choices: [
      { choiceText: "Choice 1", isCorrect: false },
      { choiceText: "Choice 2", isCorrect: false },
      { choiceText: "Choice 3", isCorrect: true },
    ],
  },
  {
    _id: "4",
    quizId: "1",
    quizQuestionType: 2,
    title: "True-False 1",
    questionText: "True-False Text 1",
    points: 1,
    correctAnswer: false,
  },
  {
    _id: "5",
    quizId: "1",
    quizQuestionType: 2,
    title: "True-False 2",
    questionText: "True-False Text 2",
    points: 1,
    correctAnswer: true,
  },
  {
    _id: "6",
    quizId: "1",
    quizQuestionType: 2,
    title: "True-False 2",
    questionText: "True-False Text 3",
    points: 1,
    correctAnswer: false,
  },
  {
    _id: "7",
    quizId: "1",
    quizQuestionType: 3,
    title: "Fill In The Blank 1",
    questionText: "Fill In The Blank Text 1",
    points: 3,
    correctAnswers: ["answer A"],
  },
  {
    _id: "8",
    quizId: "1",
    quizQuestionType: 3,
    title: "Fill In The Blank 2",
    questionText: "Fill In The Blank Text 2",
    points: 3,
    correctAnswers: ["answer B"],
  },
  {
    _id: "9",
    quizId: "1",
    quizQuestionType: 3,
    title: "Fill In The Blank 2",
    questionText: "Fill In The Blank Text 3",
    points: 3,
    correctAnswers: ["answer C", "answer D"],
  }
];
